-- ============================================================
--  METALÚRGICA OLIVEIRA — Script SQL para Supabase
--  Execute no Supabase: SQL Editor → New Query → Run
-- ============================================================

-- 1. Adicionar campos na tabela clientes (caso ainda não existam)
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cidade VARCHAR(100);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(30);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ DEFAULT NOW();

-- 2. Tabela de Pedidos / Vendas de Galpões
CREATE TABLE IF NOT EXISTS pedidos_vendas (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    descricao_galpao VARCHAR(255) NOT NULL,
    medidas_largura NUMERIC(6,2),
    medidas_comprimento NUMERIC(6,2),
    pe_direito NUMERIC(6,2),
    materiais_especificacoes TEXT,
    valor_total NUMERIC(12,2) NOT NULL,
    status_fabricacao VARCHAR(50) DEFAULT 'Em Fabricação',
    status_pagamento VARCHAR(50) DEFAULT 'Pendente',
    data_venda DATE DEFAULT CURRENT_DATE,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Pagamentos e Comprovantes
CREATE TABLE IF NOT EXISTS pagamentos_pedidos (
    id_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT REFERENCES pedidos_vendas(id_pedido) ON DELETE CASCADE,
    data_pagamento DATE NOT NULL DEFAULT CURRENT_DATE,
    valor_pago NUMERIC(12,2) NOT NULL,
    forma_pagamento VARCHAR(50) NOT NULL,
    comprovante_url TEXT,
    observacao VARCHAR(255),
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Habilitar Row Level Security e criar políticas de acesso
ALTER TABLE pedidos_vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagamentos_pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;

-- Políticas: permitir tudo para a anon key (admin protegido por senha no front-end)
CREATE POLICY "allow_all_clientes" ON clientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_produtos" ON produtos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_pedidos" ON pedidos_vendas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_pagamentos" ON pagamentos_pedidos FOR ALL USING (true) WITH CHECK (true);
